### ISSUE TITLE
Golden Gate & Project Connected Home over IP

### ISSUE THREAD

**Issue by glerchundi** [Fitbit/golden-gate#12]
First of all, I would like to thank you all for making this project publicly available. It's amazing to see these kind of projects being open sourced as, in my humble opinion, could be differentiator elements with other competitors in the same market. Even so, you decided to open source it and I firmly believe it's a much better strategy than keeping it behind your fences!

So just a big shoutout to the people it make this a reality 🙏!

Recently we found ourselves in the same situation as yours, trying to see how would be the best way "democratize" the communication with the IoT park we already have deployed. As the kind of IoT devices are getting more and more complex, the need for a better and customisable/composable RPC system is becoming a must.

Before landing to this project, we reach to the same destination as you did, that is:
* Don't reinvent the wheel and use standard protocols: CoAP, DTLS
* Custom BLE layer to achieve reliability with Android devices
* Ability to communicate between different parties ({Desktop,Web,Android,iOS,Cloud}<->IoT)
* Have a clear separation of concerns to make layers pluggable (i.e. remove DTLS because we know the transport/application already provides end-to-end security)
* ...

We are in the early stage of this evaluation but we've big concerns about where does this project laids on regarding to Project Connected Home over IP (CHIP) as it seems to be the final standarisation the IoT world needed for years. 

I'm not personally part of the alliance but it seems the idea is to embrace Thread+Zigbee (solving most requirements for all layers link/network<->application) and make it as open as possible through CHIP. That probably means that they are also going to somehow make the "ZigBee Cluster Library" theirs and adapt it to solve most of the application use cases. Although this doesn't solve all of our use cases I wanted to know what do you think about this, as you probably have a clear long term vision on this.

As an outsider I'm (I didn't found the time to get deeper in the code/docs), it seems like you decided to use standard protocols and create a custom solution around them. In case CHIP (& Thread) finally wons this IoT protocol battle, where does this project stands?

Thanks again and keep up the good work! I will follow it closely 👀!

**Comment by barbibulle** [comment]
Hi @glerchundi. Thanks for the comments.
We're also outside observers of the CHIP alliance at this point, so we don't know what it will end up specifying, or when. But it is safe to say that the direction CHIP is going in is, at least on paper, very much in line with the architecture we've been working with and deploying for a while. So my hope is that as CHIP releases some specs, that we can try an reuse a lot of our framework code to become compatible with it. There are two parts to what we've shared: 1/ a set of fairly generic components, that can run on many platforms, and be used to build IP-oriented network stacks, with a focus towards secure CoAP-based application protocols with an async-io model, and 2/ some specific way to use BLE in order to tunnel IP packets from a phone to an IoT device over BLE/GATT, because GATT is the only BLE protocol offered on mobile phones. If CHIP ends up with something similar, or if iOS/Android eventually opens up something like the IPCP profile, then we would want to evolve our project to take advantage of it, allowing to keep the upper layer implementations intact. So, in a nutshell, I would expect this project and what eventually comes out of CHIP to become compatible over time. But we're not waiting ;-)

**Comment by glerchundi** [comment]
Thanks for taking the time to answer @barbibulle!

Good to see that we're aligned in this matter. We are going to get into much more detail in the following weeks so expect some follow-up issues ;-)

Just one last question about where to ask about these kind of design doubts, is GitHub issues the best place to get in touch with you & your team or do you have/prefer any other communication tool (Slack, forum, ...)?

**Comment by barbibulle** [comment]
@glerchundi Yes, GitHub is a good place to start with any questions you have. We may setup a forum and/or slack channel later on, but for now this is the best way.

**Comment by glerchundi** [comment]
Perfect, thanks again!
